import { FormEvent, useEffect, useState, type ReactNode } from "react";
import { ArrowUpRight, Plus, Search } from "lucide-react";
import { listAuditLogs } from "../api/auditApi";
import { listHospitals } from "../api/hospitalsApi";
import { listInventory } from "../api/inventoryApi";
import { createRequest, listRequests } from "../api/requestsApi";
import { processRequest } from "../api/algorithmsApi";
import { listRoutes } from "../api/routesApi";
import { DataSource } from "../components/ui/DataSource";
import { Badge, urgencyTone } from "../components/ui/Badge";
import { Panel, SectionHeader } from "../components/ui/Panel";
import { NetworkMap } from "../components/hospitals/NetworkMap";
import { bloodGroups } from "../data/demoData";

type ResourceState<T> = { data: T; loading: boolean; error: string };
function useResource<T>(loader: () => Promise<{ data: { data: T } }>, fallback: T): ResourceState<T> { const [state, setState] = useState<ResourceState<T>>({ data: fallback, loading: true, error: "" }); useEffect(() => { loader().then((response) => setState({ data: response.data.data, loading: false, error: "" })).catch((reason) => setState({ data: fallback, loading: false, error: reason?.message ?? "Unable to load backend data" })); }, [loader]); return state; }
function Frame({ title, eyebrow, description, children, live, error, action }: { title: string; eyebrow: string; description: string; children: ReactNode; live: boolean; error?: string; action?: ReactNode }) { return <><div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div><div><DataSource live={live} error={error} />{action}</div></div>{children}<div className="page-footnote"><span>{live ? "BACKEND DATA" : "DEMO FALLBACK"}</span>{live ? " Loaded from the Flask API." : " Backend endpoint unavailable; no silent data mixing."}</div></>; }
function Table({ headers, rows }: { headers: string[]; rows: ReactNode[][] }) { return <div className="table-scroll"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>; }
export function LiveRequests() { const resource = useResource(listRequests, []); const [showForm, setShowForm] = useState(false); return <Frame title="Blood requests" eyebrow="Request coordination" description="Prioritize and track emergency requests from the backend database." live={!resource.error && !resource.loading} error={resource.error} action={<button className="button primary" onClick={() => setShowForm(true)}><Plus size={16} /> Create emergency request</button>}>{showForm && <RequestForm onDone={() => setShowForm(false)} />}{resource.loading ? <Panel><div className="empty-state">Loading requests...</div></Panel> : resource.error ? <Panel><div className="empty-state"><strong>Unable to load requests</strong><span>{resource.error}</span></div></Panel> : <Panel><SectionHeader title="Request queue" /><Table headers={["Request ID", "Blood / units", "Urgency", "Requested at", "Hospital", "Status", ""]} rows={resource.data.map((item: any) => [<strong>REQ-{item.id}</strong>, <strong>{item.blood_group} · {item.required_units} units</strong>, <Badge tone={urgencyTone(item.urgency)}>{item.urgency}</Badge>, new Date(item.created_at).toLocaleString(), `Hospital #${item.requesting_hospital_id}`, <Badge tone={urgencyTone(item.status)}>{item.status}</Badge>, <button className="icon-button"><ArrowUpRight size={16} /></button>])} /></Panel>}</Frame>; }
function RequestForm({ onDone }: { onDone: () => void }) { const [values, setValues] = useState({ blood_group: "O+", required_units: "1", urgency: "CRITICAL", requesting_hospital_id: "1", notes: "" }); const [state, setState] = useState(""); const [result, setResult] = useState<any>(null); const submit = async (event: FormEvent) => { event.preventDefault(); setResult(null); setState("Submitting and processing through BFS, Greedy and A*..."); try { const created = await createRequest({ ...values, required_units: Number(values.required_units), requesting_hospital_id: Number(values.requesting_hospital_id) }); const processed = await processRequest(created.data.data.id); setResult(processed.data.data); setState(`Request REQ-${created.data.data.id} processed: ${processed.data.data.status}.`); } catch (reason: any) { setState(reason?.message ?? "Unable to process request"); } }; return <Panel className="request-form"><SectionHeader title="Create emergency request" description="Validated and processed by the backend workflow." /><form onSubmit={submit}><div className="form-grid"><label className="form-label">Blood group<select value={values.blood_group} onChange={(event) => setValues({ ...values, blood_group: event.target.value })}>{bloodGroups.map((group) => <option key={group}>{group}</option>)}</select></label><label className="form-label">Required units<input type="number" min="1" value={values.required_units} onChange={(event) => setValues({ ...values, required_units: event.target.value })} /></label><label className="form-label">Urgency<select value={values.urgency} onChange={(event) => setValues({ ...values, urgency: event.target.value })}><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>NORMAL</option></select></label><label className="form-label">Destination hospital ID<input type="number" min="1" value={values.requesting_hospital_id} onChange={(event) => setValues({ ...values, requesting_hospital_id: event.target.value })} /></label><label className="form-label">Notes<textarea value={values.notes} maxLength={2000} onChange={(event) => setValues({ ...values, notes: event.target.value })} /></label></div>{state && <p className="form-state">{state}</p>}<button className="button primary" type="submit">Submit and process request</button></form>{result && <div className="workflow-result"><strong>Request REQ-{result.request.id}</strong><span>Requested: {result.allocation.required_units} units</span><span>Allocated: {result.allocation.allocated_units} units</span><span>Status: {result.status}</span><div><i>✓</i> Priority calculated</div><div><i>✓</i> Nearby hospitals found: {result.bfs.traversal_order.length}</div><div><i>✓</i> Compatible blood found: {result.allocation.compatible_donor_groups.join(", ")}</div><div><i>✓</i> Blood allocated</div><div><i>✓</i> Route calculated</div><div><i>✓</i> Inventory updated</div><div><i>✓</i> Dispatch created: {result.dispatch.id}</div></div>}</Panel>; }
export function LiveHospitals() { const resource = useResource(listHospitals, []); return <Frame title="Hospital network" eyebrow="Connected care network" description="Hospital records and coordinates from the backend." live={!resource.error && !resource.loading} error={resource.error}><Panel>{resource.loading ? <div className="empty-state">Loading hospitals...</div> : resource.error ? <div className="empty-state">Unable to load hospital data.</div> : <Table headers={["Hospital", "ID", "Location", "Latitude", "Longitude", "Status"]} rows={resource.data.map((item: any) => [<strong>{item.name}</strong>, item.code, item.address ?? "-", item.latitude, item.longitude, <Badge tone={item.status === "ACTIVE" ? "success" : "neutral"}>{item.status}</Badge>])} />}</Panel><Panel className="network-detail"><SectionHeader title="Hospital network map" description="Coordinates loaded from backend records. Connection overlays remain demo until route graph API is expanded." /><NetworkMap /></Panel></Frame>; }
export function LiveInventory() { const resource = useResource(listInventory, []); const grouped = bloodGroups.map((group) => ({ group, units: resource.data.filter((item: any) => item.blood_group === group).reduce((sum: number, item: any) => sum + item.units_available, 0) })); return <Frame title="Inventory overview" eyebrow="Blood bank readiness" description="Actual inventory rows from the backend database." live={!resource.error && !resource.loading} error={resource.error}><div className="inventory-strip">{grouped.slice(0, 4).map((item) => <div className="inventory-mini" key={item.group}><span className="blood-chip">{item.group}</span><strong>{resource.loading ? "..." : item.units}</strong><small>backend units</small><div className="meter"><i style={{ width: `${Math.min(100, item.units * 2)}%` }} /></div></div>)}</div><Panel>{resource.loading ? <div className="empty-state">Loading inventory...</div> : resource.error ? <div className="empty-state">Unable to load inventory data.</div> : <Table headers={["Hospital ID", "Blood group", "Available units", "Updated"]} rows={resource.data.map((item: any) => [item.hospital_id, <span className="blood-chip">{item.blood_group}</span>, <strong>{item.units_available}</strong>, item.updated_at ? new Date(item.updated_at).toLocaleString() : "-" ])} />}</Panel></Frame>; }
export function LiveRoutes() { const resource = useResource(listRoutes, []); return <Frame title="Routes & dispatch" eyebrow="Movement control" description="Persisted route records from processed requests." live={!resource.error && !resource.loading} error={resource.error}><Panel className="route-map"><SectionHeader title="Dispatch network" description="Map uses demo network until route coordinates are returned by the backend." /><NetworkMap /></Panel><Panel>{resource.loading ? <div className="empty-state">Loading routes...</div> : resource.error ? <div className="empty-state">Unable to load route data.</div> : <Table headers={["Route", "Origin", "Destination", "Distance", "Travel estimate", "Path"]} rows={resource.data.map((item: any) => [<strong>ROUTE-{item.id}</strong>, item.source_hospital_id, item.destination_hospital_id, `${item.distance_km} km`, `${item.estimated_minutes} min`, item.path.join(" → ")])} />}</Panel></Frame>; }
export function LiveAudit() { const resource = useResource(listAuditLogs, []); return <Frame title="Audit logs" eyebrow="Security trail" description="Redacted audit records from the backend." live={!resource.error && !resource.loading} error={resource.error}><Panel>{resource.loading ? <div className="empty-state">Loading audit logs...</div> : resource.error ? <div className="empty-state">Unable to load audit data.</div> : <Table headers={["Timestamp", "User", "Action", "Resource", "IP / metadata"]} rows={resource.data.map((item: any) => [item.created_at ? new Date(item.created_at).toLocaleString() : "-", item.user_id ?? "System", <strong className="mono">{item.action}</strong>, `${item.entity} ${item.entity_id ?? ""}`, item.ip_address ?? "-"]) } />}</Panel></Frame>; }
