import { useState, type ReactNode } from "react";
import { ArrowRight, Check, CirclePlay, GitBranch, RotateCcw } from "lucide-react";
import { runAstar, runBfs, runGreedy, runPriority } from "../api/algorithmsApi";
import { Badge } from "../components/ui/Badge";
import { DataSource } from "../components/ui/DataSource";
import { Panel, SectionHeader } from "../components/ui/Panel";

const tabs = ["BFS", "Red-Black Tree", "Greedy Allocation", "A*"];
export default function LiveAlgorithms() { const [active, setActive] = useState("BFS"); return <><div className="page-heading algorithm-heading"><div><p className="eyebrow">Algorithm center · backend execution</p><h1>Core routing intelligence</h1><p>Actual results from the existing Flask algorithm endpoints.</p></div><DataSource live /></div><div className="algorithm-tabs">{tabs.map((tab) => <button className={active === tab ? "selected" : ""} onClick={() => setActive(tab)} key={tab}>{tab}</button>)}</div>{active === "BFS" && <Bfs />}{active === "Red-Black Tree" && <Priority />}{active === "Greedy Allocation" && <Greedy />}{active === "A*" && <Astar />}</> }
function Bfs() { const [result, setResult] = useState<any>(null); const [error, setError] = useState(""); const run = async () => { try { setError(""); setResult((await runBfs({ source_hospital_id: 1 })).data.data); } catch (reason: any) { setError(reason.message); } }; const order = result?.traversal_order ?? []; return <AlgorithmPanel title="Hospital discovery graph" eyebrow="Breadth-first search" description="Queue traversal from hospital 1 using the backend graph." error={error}><div className="graph-canvas">{Object.keys(result?.graph ?? { H1: [], H2: [], H3: [], H4: [], H5: [], H6: [] }).slice(0, 6).map((node, index) => <div key={node} className={`graph-node node-H${index + 1} ${order.includes(Number(node) || node) ? "visited" : ""}`}><span>{node.startsWith("H") ? node : `H${node}`}</span><small>{index === 0 ? "Source" : "Hospital"}</small></div>)}<div className="graph-lines" /></div><Controls run={run} reset={() => setResult(null)} /><div className="metric-block"><span>Visited order</span><strong>{order.length ? order.join(" → ") : "Run BFS to load actual traversal"}</strong></div><div className="algorithm-note"><Check size={15} /> Time O(V + E) · Space O(V) · backend graph result</div></AlgorithmPanel> }
function Priority() { const [result, setResult] = useState<any>(null); const [error, setError] = useState(""); const run = async () => { try { setError(""); setResult((await runPriority()).data.data); } catch (reason: any) { setError(reason.message); } }; return <AlgorithmPanel title="Request priority tree" eyebrow="Red-Black Tree" description="The backend tree remains the source of truth for priority and node colors." error={error}><div className="tree-canvas"><div className="tree-node black-node">{result?.highest_priority ? `REQ-${result.highest_priority}` : "Awaiting"}<span>Highest priority</span></div><div className="tree-branch left" /><div className="tree-branch right" /><div className="tree-node red-node left-child">Backend<span>Red node</span></div><div className="tree-node black-node right-child">Backend<span>Black node</span></div></div><Controls run={run} reset={() => setResult(null)} /><div className="metric-block"><span>Returned tree</span><strong>{result ? "Actual serialized priority tree loaded" : "Run priority to load request tree"}</strong></div><div className="algorithm-note"><GitBranch size={15} /> Insert/search/delete remain implemented only in the backend.</div></AlgorithmPanel> }
function Greedy() { const [result, setResult] = useState<any>(null); const [error, setError] = useState(""); const run = async () => { try { setError(""); setResult((await runGreedy({ blood_group: "O+", required_units: 12 })).data.data); } catch (reason: any) { setError(reason.message); } }; return <AlgorithmPanel title="Greedy blood allocation" eyebrow="Allocation strategy" description="The backend selects maximum currently available compatible inventory first." error={error}><div className="required-total"><span>Required</span><strong>12 <small>O+ units</small></strong><Badge tone="info">{result ? `${result.allocated_units} / 12 allocated` : "Awaiting backend"}</Badge></div><Controls run={run} reset={() => setResult(null)} />{result ? <div className="allocation-steps">{result.allocation_steps.map((step: any, index: number) => <div className="complete" key={step.hospital_id}><span>{index + 1}</span><p><strong>Hospital {step.hospital_id} selected</strong><small>{step.units_taken} units taken · {step.remaining_required} remaining</small></p></div>)}</div> : <div className="empty-state">Run allocation to display actual hospital selections.</div>}</AlgorithmPanel> }
function Astar() { const [result, setResult] = useState<any>(null); const [error, setError] = useState(""); const run = async () => { try { setError(""); setResult((await runAstar({ source_hospital_id: 2, destination_hospital_id: 1 })).data.data); } catch (reason: any) { setError(reason.message); } }; return <AlgorithmPanel title="A* pathfinding" eyebrow="Route optimization" description="Actual distance cost, estimated travel time, and score maps from Flask." error={error}><div className="astar-grid">{Array.from({ length: 48 }, (_, index) => <span className={result?.path?.includes(index + 1) ? "route" : ""} key={index}>{index === 1 ? "S" : index === 0 ? "D" : ""}</span>)}</div><Controls run={run} reset={() => setResult(null)} /><div className="score-table"><div><span>Path</span><strong>{result?.path?.join(" → ") ?? "-"}</strong></div><div><span>Distance</span><strong>{result?.distance != null ? `${result.distance} km` : "-"}</strong></div><div><span>Estimated time</span><strong>{result?.estimated_time != null ? `${result.estimated_time} min` : "-"}</strong></div></div><p className="algorithm-disclaimer">Haversine distance is used as a geographic heuristic. This does not represent live traffic.</p></AlgorithmPanel> }
function Controls({ run, reset }: { run: () => void; reset: () => void }) { return <div className="algorithm-controls"><button className="button primary" onClick={run}><CirclePlay size={16} /> Run backend algorithm</button><button className="button secondary" onClick={reset}><RotateCcw size={16} /> Reset</button></div>; }
function AlgorithmPanel({ title, eyebrow, description, error, children }: { title: string; eyebrow: string; description: string; error: string; children: ReactNode }) { return <div className="algorithm-layout"><Panel className="algorithm-visual"><SectionHeader eyebrow={eyebrow} title={title} description={description} />{error && <div className="login-error">{error}</div>}{children}</Panel><Panel className="algorithm-side"><SectionHeader title="Execution contract" /><div className="metric-block"><span>Source of truth</span><strong>Flask backend algorithm service</strong></div><div className="metric-block"><span>Result handling</span><strong>No client-side algorithm result generation</strong></div><div className="algorithm-note"><Check size={15} /> Actual API response displayed in the approved visualizer</div></Panel></div>; }
