"""initial schema

Revision ID: 29a9509fc691
Revises: 
Create Date: 2026-09-19 11:47:45.684885
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '29a9509fc691'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_code'), 'hospitals', ['code'], unique=True)
    op.create_index(op.f('ix_hospitals_status'), 'hospitals', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('blood_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=3), nullable=False),
    sa.Column('units_available', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('units_available >= 0'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'blood_group')
    )
    op.create_index(op.f('ix_blood_inventory_blood_group'), 'blood_inventory', ['blood_group'], unique=False)
    op.create_index(op.f('ix_blood_inventory_hospital_id'), 'blood_inventory', ['hospital_id'], unique=False)
    op.create_table('blood_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requesting_hospital_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=3), nullable=False),
    sa.Column('required_units', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('required_units > 0'),
    sa.ForeignKeyConstraint(['requesting_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_requests_blood_group'), 'blood_requests', ['blood_group'], unique=False)
    op.create_index(op.f('ix_blood_requests_created_at'), 'blood_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_blood_requests_requesting_hospital_id'), 'blood_requests', ['requesting_hospital_id'], unique=False)
    op.create_index(op.f('ix_blood_requests_status'), 'blood_requests', ['status'], unique=False)
    op.create_index(op.f('ix_blood_requests_urgency'), 'blood_requests', ['urgency'], unique=False)
    op.create_table('hospital_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_hospital_id', sa.Integer(), nullable=False),
    sa.Column('destination_hospital_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['destination_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['source_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hospital_id', 'destination_hospital_id')
    )
    op.create_index(op.f('ix_hospital_connections_destination_hospital_id'), 'hospital_connections', ['destination_hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_connections_source_hospital_id'), 'hospital_connections', ['source_hospital_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('units_allocated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['blood_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_hospital_id'), 'allocations', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_allocations_request_id'), 'allocations', ['request_id'], unique=False)
    op.create_table('blood_inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('change_units', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['blood_inventory.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['blood_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_inventory_transactions_inventory_id'), 'blood_inventory_transactions', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_blood_inventory_transactions_request_id'), 'blood_inventory_transactions', ['request_id'], unique=False)
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['blood_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_request_id'), 'dispatches', ['request_id'], unique=False)
    op.create_index(op.f('ix_dispatches_status'), 'dispatches', ['status'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('source_hospital_id', sa.Integer(), nullable=False),
    sa.Column('destination_hospital_id', sa.Integer(), nullable=False),
    sa.Column('path_json', sa.JSON(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['blood_requests.id'], ),
    sa.ForeignKeyConstraint(['source_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_request_id'), 'routes', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_request_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_dispatches_status'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_request_id'), table_name='dispatches')
    op.drop_table('dispatches')
    op.drop_index(op.f('ix_blood_inventory_transactions_request_id'), table_name='blood_inventory_transactions')
    op.drop_index(op.f('ix_blood_inventory_transactions_inventory_id'), table_name='blood_inventory_transactions')
    op.drop_table('blood_inventory_transactions')
    op.drop_index(op.f('ix_allocations_request_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_hospital_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_hospital_connections_source_hospital_id'), table_name='hospital_connections')
    op.drop_index(op.f('ix_hospital_connections_destination_hospital_id'), table_name='hospital_connections')
    op.drop_table('hospital_connections')
    op.drop_index(op.f('ix_blood_requests_urgency'), table_name='blood_requests')
    op.drop_index(op.f('ix_blood_requests_status'), table_name='blood_requests')
    op.drop_index(op.f('ix_blood_requests_requesting_hospital_id'), table_name='blood_requests')
    op.drop_index(op.f('ix_blood_requests_created_at'), table_name='blood_requests')
    op.drop_index(op.f('ix_blood_requests_blood_group'), table_name='blood_requests')
    op.drop_table('blood_requests')
    op.drop_index(op.f('ix_blood_inventory_hospital_id'), table_name='blood_inventory')
    op.drop_index(op.f('ix_blood_inventory_blood_group'), table_name='blood_inventory')
    op.drop_table('blood_inventory')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hospitals_status'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_code'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
