"""add request notes

Revision ID: 828b63ec7d99
Revises: e822f5b2fa03
Create Date: 2026-09-19 13:06:34.178747
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '828b63ec7d99'
down_revision: Union[str, Sequence[str], None] = 'e822f5b2fa03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_requests', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blood_requests', 'notes')
    # ### end Alembic commands ###
